export const poData = [
  {
    id: 1,
    purchaseOrderNumber: "29645-CD",
    unit: "T4",
    emailDate: "2024-07-19",
    teams: 23,
    teamDetail: [
      {
        teamName: "arkansas",
        bodyColor: "black",
        artworkColors: ["499", "234"],
        actualQuantity: 234,
        quantityForPrint: 244,
        quantityPrinted: 244,
        strikeOff: true,
        ppSample: true,
      },
    ],
    items: "front",
    strikeOff: true,
    ppSample: true,
    requiredQuantity: 345,
    purchaseOrderQuantity: 500,
    quantityForPrint: 450,
    quantityPrinted: 15450,
    clientPurchaseOrderNumber: "1163/45",
    shipmentDate: "2024-6-15",
    quatityForBilling: 450,
    rate: 45,
    invoiceNumber: 10001,
    lastModified: null,
  },
  {
    id: 2,
    purchaseOrderNumber: "29656-CD",
    unit: "T4",
    emailDate: "2024-07-19",
    teams: 23,
    teamDetail: [
      {
        teamName: "arkansas",
        bodyColor: "black",
        artworkColors: ["499", "234"],
        actualQuantity: 234,
        quantityForPrint: 244,
        quantityPrinted: 244,
        strikeOff: true,
        ppSample: true,
      },
    ],
    items: "front",
    strikeOff: false,
    ppSample: false,
    requiredQuantity: 345,
    purchaseOrderQuantity: 500,
    quantityForPrint: 450,
    quantityPrinted: 15450,
    clientPurchaseOrderNumber: "1163/45",
    shipmentDate: "2024-6-15",
    quatityForBilling: 450,
    rate: 45,
    invoiceNumber: 10001,
    lastModified: null,
  },
  {
    id: 3,
    purchaseOrderNumber: "29645-aB",
    unit: "T4",
    emailDate: "2024-07-19",
    teams: 23,
    teamDetail: [
      {
        teamName: "arkansas",
        bodyColor: "black",
        artworkColors: ["499", "234"],
        actualQuantity: 234,
        quantityForPrint: 244,
        quantityPrinted: 244,
        strikeOff: true,
        ppSample: true,
      },
    ],
    items: "front",
    strikeOff: false,
    ppSample: false,
    requiredQuantity: 345,
    purchaseOrderQuantity: 500,
    quantityForPrint: 450,
    quantityPrinted: 15450,
    clientPurchaseOrderNumber: "1163/45",
    shipmentDate: "2024-6-15",
    quatityForBilling: 450,
    rate: 45,
    invoiceNumber: 10001,
    lastModified: null,
  },
  {
    id: 4,
    purchaseOrderNumber: "296adaa",
    unit: "T4",
    emailDate: "2024-07-19",
    teams: 23,
    teamDetail: [
      {
        teamName: "arkansas",
        bodyColor: "black",
        artworkColors: ["499", "234"],
        actualQuantity: 234,
        quantityForPrint: 244,
        quantityPrinted: 244,
        strikeOff: true,
        ppSample: true,
      },
    ],
    items: "front",
    strikeOff: true,
    ppSample: true,
    requiredQuantity: 345,
    purchaseOrderQuantity: 500,
    quantityForPrint: 450,
    quantityPrinted: 15450,
    clientPurchaseOrderNumber: "1163/45",
    shipmentDate: "2024-6-15",
    quatityForBilling: 450,
    rate: 45,
    invoiceNumber: 10001,
    lastModified: null,
  },
];
